name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the app code
      uses: actions/checkout@v3
      
    - name: Build the app docker image
      run: |
        docker build -t basselmanasrah/final-python:${{ github.run_number }}-${{ github.sha }} .
        docker tag basselmanasrah/final-python:${{ github.run_number}}-${{ github.sha }} basselmanasrah/final-python:latest
        
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      
    - name: Push app docker image to registry
      run: |
        docker push basselmanasrah/final-python:${{ github.run_number }}-${{ github.sha }}
        docker push basselmanasrah/final-python
